### ISSUE TITLE
Blurry interface on Windows

### ISSUE THREAD

**Issue by GioPat** [alexislozano/neutrino#73]
After setting up a simple UI with just a menu, I realized that the text is a bit blurry (small resolution). 
This is a screen shot:
![neutrino_blurry](https://user-images.githubusercontent.com/9217515/70378690-ae79f780-1923-11ea-9e97-52102e06ba78.png)

These are my system specification:
![image](https://user-images.githubusercontent.com/9217515/70378697-b89bf600-1923-11ea-9d8f-cabc66fbe33a.png)

**Comment by alexislozano** [comment]
Hello !

I don't know exactly why it is happening. Some ideas though :
- Are you using a HiDPI screen (more than 1080p) ?
- Each theme (CSS) has a different font, maybe you should try to use the Fluent theme, it was specifically designed for W10.
- Otherwise, you could try to change the font used using CSS theming.

Here are the docs for theming : 
[https://docs.rs/neutrino/0.3.1/neutrino/utils/theme/enum.Theme.html](https://docs.rs/neutrino/0.3.1/neutrino/utils/theme/enum.Theme.html) and [https://docs.rs/neutrino/0.3.1/neutrino/struct.Window.html#method.set_theme](https://docs.rs/neutrino/0.3.1/neutrino/struct.Window.html#method.set_theme)

Let me know if you have more questions :)

**Comment by GioPat** [comment]
> Hello !
> 
> I don't know exactly why it is happening. Some ideas though :
> 
> * Are you using a HiDPI screen (more than 1080p) ?
> * Each theme (CSS) has a different font, maybe you should try to use the Fluent theme, it was specifically designed for W10.
> * Otherwise, you could try to change the font used using CSS theming.
> 
> Here are the docs for theming :
> https://docs.rs/neutrino/0.3.1/neutrino/utils/theme/enum.Theme.html and https://docs.rs/neutrino/0.3.1/neutrino/struct.Window.html#method.set_theme
> 
> Let me know if you have more questions :)

Thanks for the fast reply!
Changing the theme is not solving the issue.
Anyway I figured out that I have 1080p resolution with the 125% zoom option selected.
If I select 100% the screen is not blurry anymore.
This is likely to be a windows problem, in fact i found [this guide](https://support.microsoft.com/en-us/help/4026996).
Just for note: activating the windows helper to avoid blurry interfaces is still not solving the issue 😕 .

Thank you!

**Comment by alexislozano** [comment]
If neutrino is not the issue here, can you close the issue ?

**Comment by GioPat** [comment]
> If neutrino is not the issue here, can you close the issue ?

Sure! I will try to figure out what's the issue ☺️

**Comment by GioPat** [comment]
Just to keep track of the issue I forwarded this to the web-view rust repo: [https://github.com/Boscop/web-view/issues/99](https://github.com/Boscop/web-view/issues/99)

**Comment by alexislozano** [comment]
Great thanks !
